### PR TITLE
Not happy with change 

### PR DESCRIPTION
**Pull request by aakash32019**

### CODE REVIEW

**Review by xv-aakash-a — CHANGES_REQUESTED** [review]
the line 1 needs to change to "Added practice to reject the change and updating the change in a PR"

**Comment by aakash32019** [comment]
ok let me change the line

**Comment by aakash32019** [comment]
Added changes to https://github.com/aakash32019/my-first-project/tree/5423d4e063209c4f809dc51f3c4f92ff5e592477

**Review by aakash32019 — COMMENTED** [review]
this looks good

**Review by xv-aakash-a — APPROVED** [review]
this looks good

**Pull request merged**
